# Generated by Django 5.1.2 on 2024-11-12 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Гарантия')),
            ],
            options={
                'verbose_name': 'Гарантия',
                'verbose_name_plural': 'Гарантии',
            },
        ),
        migrations.CreateModel(
            name='QualificationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Квалификация автора')),
            ],
            options={
                'verbose_name': 'Квалификация автора',
                'verbose_name_plural': 'Квалификации авторов',
            },
        ),
        migrations.CreateModel(
            name='Shrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Шрифт')),
            ],
            options={
                'verbose_name': 'Шрифт',
                'verbose_name_plural': 'Шрифты',
            },
        ),
        migrations.CreateModel(
            name='TypeConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип консультации')),
            ],
            options={
                'verbose_name': 'Тип консультации',
                'verbose_name_plural': 'Типы консультаций',
            },
        ),
        migrations.CreateModel(
            name='OrderWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_order', models.CharField(max_length=250, verbose_name='Номер заказа')),
                ('item', models.CharField(max_length=250, verbose_name='Предмет')),
                ('theme', models.CharField(max_length=250, verbose_name='Тема')),
                ('min_page_size', models.IntegerField(default=0, verbose_name='Минимальный объем страниц')),
                ('number_of_sources_literature', models.IntegerField(default=0, verbose_name='Количество источников литературы')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, null=True, upload_to='order_work/', verbose_name='Файл')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL, verbose_name='Автор заказа')),
                ('guarantee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_guarantee', to='cyberdoc.guarantee', verbose_name='Гарантия')),
                ('qualification_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_qualification_author', to='cyberdoc.qualificationauthor', verbose_name='Квалификация автора')),
                ('shrift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_shrift', to='cyberdoc.shrift', verbose_name='Шрифт')),
                ('type_cons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_type_conf', to='cyberdoc.typeconsultation', verbose_name='Тип консультации')),
            ],
            options={
                'verbose_name': 'Заказ на работу',
                'verbose_name_plural': 'Заказы на работу',
            },
        ),
    ]
