# Generated by Django 5.1.2 on 2024-11-12 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberdoc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guarantee',
            options={'verbose_name': '4. Гарантия', 'verbose_name_plural': '4. Гарантии'},
        ),
        migrations.AlterModelOptions(
            name='orderwork',
            options={'verbose_name': '5. Заказ на работу', 'verbose_name_plural': '5. Заказы на работу'},
        ),
        migrations.AlterModelOptions(
            name='qualificationauthor',
            options={'verbose_name': '2. Квалификация автора', 'verbose_name_plural': '2. Квалификации авторов'},
        ),
        migrations.AlterModelOptions(
            name='shrift',
            options={'verbose_name': '3. Шрифт', 'verbose_name_plural': '3. Шрифты'},
        ),
        migrations.AlterModelOptions(
            name='typeconsultation',
            options={'verbose_name': '1. Тип консультации', 'verbose_name_plural': '1. Типы консультаций'},
        ),
        migrations.AddField(
            model_name='orderwork',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.CreateModel(
            name='OrderWorkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Оценка')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('order_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cyberdoc.orderwork', verbose_name='Заказ на работу')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв на заказ на работу',
                'verbose_name_plural': 'Отзывы на заказы на работу',
                'ordering': ['-rating'],
            },
        ),
    ]
