# Generated by Django 5.1.2 on 2024-11-12 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberdoc', '0002_alter_guarantee_options_alter_orderwork_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderworkreview',
            options={'ordering': ['-rating'], 'verbose_name': '6. Отзыв на заказ на работу', 'verbose_name_plural': '6. Отзывы на заказы на работу'},
        ),
        migrations.CreateModel(
            name='DescribeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_problem', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Описание проблемы',
                'verbose_name_plural': 'Описания проблем',
            },
        ),
    ]
