# Generated by Django 5.1.2 on 2024-11-21 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberdoc', '0003_alter_orderworkreview_options_describeproblem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderwork',
            name='file',
        ),
        migrations.CreateModel(
            name='OrderWorkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='order_work/', verbose_name='Файл')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('order_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_work_file', to='cyberdoc.orderwork', verbose_name='Заказ на работу')),
            ],
        ),
    ]
