# Generated by Django 5.1.2 on 2024-11-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberdoc', '0004_remove_orderwork_file_orderworkfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderwork',
            name='foreign_sources',
            field=models.BooleanField(blank=True, null=True, verbose_name='Иностранные источники'),
        ),
    ]
