# Generated by Django 5.1.2 on 2024-11-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberdoc', '0006_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='describeproblem',
            options={'verbose_name': '7. Описание проблемы', 'verbose_name_plural': '7. Описания проблем'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': '8. Пользователь портфолио', 'verbose_name_plural': '8. Пользователь портфолио'},
        ),
        migrations.AddField(
            model_name='orderwork',
            name='is_activate',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус'),
        ),
    ]
