# Generated by Django 5.1.2 on 2024-11-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
    ]
