# Generated by Django 5.1.2 on 2024-11-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conf_site', '0003_serviceblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '1. Услуга', 'verbose_name_plural': '1. Услуга'},
        ),
        migrations.AlterModelOptions(
            name='serviceblog',
            options={'verbose_name': '2. Блог услуги', 'verbose_name_plural': '2. Блоги услуг'},
        ),
        migrations.AlterModelOptions(
            name='submitrequest',
            options={'verbose_name': '3. Отправить заявку', 'verbose_name_plural': '3. Отправить заявку'},
        ),
    ]
